apiVersion: v2
name: github-arc-runner-prerequisite
description: Helm chart that deploys GitHub Actions RunnerSets Prerequisites
type: application
version: 0.1.0
appVersion: 1.0.0
maintainers:
  - name: Dr Magel

