{{ $name := .Release.Name }}
{{ $namespace := .Release.Namespace }}

{{ with .Values.controller.secret }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  vaultAuthGlobalRef:
    allowDefault: true
    namespace: vault

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $name }}-secret
  namespace: {{ $namespace }}
spec:
  vaultAuthRef: {{ $name }}
  type: kv-v2
  mount: {{ .mount }}
  path: {{ .path }}
  destination:
    name: {{ .name }}
    create: true
  refreshAfter: "60s"
{{ end }}