apiVersion: v2
name: arc-controller
description: Helm umbrella chart that deploys GitHub Actions Runner Controller
type: application
version: 0.1.0
appVersion: 1.0.0
maintainers:
  - name: Dr Magel
dependencies:
  - name: gha-runner-scale-set-controller
    version: "0.13.0"
    repository: "oci://ghcr.io/actions/actions-runner-controller-charts"
