{{ $name := "arc-runner" }}
{{ $namespace := .Release.Namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
---
# 2. Grant 'admin' permissions within the {{ $namespace }} namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
subjects:
- kind: ServiceAccount
  name: {{ $name }}
  namespace: {{ $namespace }}
roleRef:
  kind: ClusterRole
  name: admin # Built-in Kubernetes role for namespace-level administrative access
  apiGroup: rbac.authorization.k8s.io
