apiVersion: v2
name: github-action-controller
description: Helm umbrella chart that deploys GitHub Actions Runner Controller
type: application
version: 0.1.0
appVersion: 1.0.0
maintainers:
  - name: Dr Magel
dependencies:
  - name: actions-runner-controller
    version: "0.23.7"
    repository: "https://actions-runner-controller.github.io/actions-runner-controller"
# # cert-manager dependency
# - name: cert-manager
#   version: "v1.19.2"
#   repository: "https://charts.jetstack.io"
